alias gis="git status"
alias gia="git add"
alias gic="git commit"
alias gip="git push"
alias gil="git log --graph --abbrev-commit --pretty=format:\"%Cred%h%Creset - %C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset\""
alias gid="git diff --minimal --color"
